name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    # Also see warning here https://github.com/cypress-io/github-action#parallel
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1, 2] # Uses 2 parallel instances
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build CI Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.ci
          target: test
          tags: sigeco-ci:latest
          load: true
          cache-from: type=gha,scope=cypress
          cache-to: type=gha,mode=max,scope=cypress
      
      - name: Start Vite dev server in background
        run: |
          docker run -d \
            --name vite-server-${{ matrix.containers }} \
            -p 9323:9323 \
            -e CI=true \
            sigeco-ci:latest \
            npm run dev
      
      - name: Wait for dev server to be ready
        run: |
          docker run --rm \
            --network host \
            sigeco-ci:latest \
            npx wait-on http://localhost:9323 --timeout 120000
      
      - name: Run Cypress tests
        run: |
          docker run --rm \
            --network host \
            -e CI=true \
            -e CYPRESS_RECORD_KEY="${{ secrets.CYPRESS_RECORD_KEY }}" \
            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -v ${{ github.workspace }}/test-results:/app/test-results:rw \
            sigeco-ci:latest \
            npm run test:cypress:ci
      
      - name: Stop Vite dev server
        if: always()
        run: docker stop vite-server-${{ matrix.containers }} || true
      
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.containers }}
          path: test-results/cypress/screenshots
          if-no-files-found: ignore
      
      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-${{ matrix.containers }}
          path: test-results/cypress/videos
          if-no-files-found: ignore
